[package]
edition = "2021"
name = "client"
version = "0.1.0"

[dependencies]
anyhow = "1"
base64 = "0.13"
clap = { version = "3", features = ["derive"] }
hex = "0.4"
log = "0.4"
simple_logger = "2"
sindri = { path = "../sindri" }
