[package]
name = "sindri"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aes-gcm = "0.9"
ecdsa = { version = "0.12", default-features = false }
elliptic-curve = { version = "0.10", default-features = false }
generic-array = { version = "0.14", default-features = false, features = ["more_lengths"] }
p256 = { version = "0.9", default-features = false, features = ["ecdh", "ecdsa"] }
rand = { version = "0.8", default-features = false }
rand_chacha = { version = "0.3", default-features = false }
rand_core = { version = "0.6", default-features = false }
sha2 = { version = "0.9" }

[dev-dependencies]
hex = { version = "0.4" }
