[package]
name = "sindri"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aes-gcm = "0.9.4"
generic-array = { version = "0.14", features = ["more_lengths"] }
sha2 = { version = "0.9.6" }

[dev-dependencies]
hex = { version = "0.4.3" }
