name: Security audit
on:
  push:
    paths:
      - '**/Cargo.toml'
      - '**/Cargo.lock'
    schedule:
        '0 0 * * *'
jobs:
  security_audit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory: [./sindri] # Only audit main crate
    steps:
      - uses: actions/checkout@v1
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          profile: minimal
          target: x86_64-unknown-linux-musl
      - name: Security Audit
        run: |
          cargo install cargo-audit
          cargo audit --file ${{ matrix.directory }}/Cargo.lock
